#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/prepare-private-fragment.sh <profile-json> <workspace-dir>

Generates common/private.fragment and common/private.required from the
CoreShift default fragment plus an optional repo-root private.fragment.
EOF
}

if [ "$#" -ne 2 ]; then
  usage >&2
  exit 1
fi

command -v python3 >/dev/null 2>&1 || {
  echo "Missing required tool: python3" >&2
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROFILE_JSON="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
WORKSPACE_DIR="$2"
COMMON_DIR="$WORKSPACE_DIR/common"
DEFAULT_FRAGMENT="$REPO_ROOT/configs/fragments/coreshift.fragment"
USER_FRAGMENT="$REPO_ROOT/private.fragment"
GENERATED_FRAGMENT="$COMMON_DIR/private.fragment"
REQUIRED_FRAGMENT="$COMMON_DIR/private.required"
BUILD_BAZEL="$COMMON_DIR/BUILD.bazel"
GKI_DEFCONFIG="$COMMON_DIR/arch/arm64/configs/gki_defconfig"
MERGE_CONFIG_SH="$COMMON_DIR/scripts/kconfig/merge_config.sh"
WRAPPER_BUILD_CONFIG="$COMMON_DIR/build.config.coreshift.gki.aarch64"

if [ ! -f "$PROFILE_JSON" ]; then
  echo "Profile not found: $PROFILE_JSON" >&2
  exit 1
fi

if [ ! -d "$COMMON_DIR" ]; then
  echo "Workspace common directory not found: $COMMON_DIR" >&2
  exit 1
fi

if [ ! -f "$DEFAULT_FRAGMENT" ]; then
  echo "CoreShift default fragment not found: $DEFAULT_FRAGMENT" >&2
  exit 1
fi

eval "$(
  python3 - "$PROFILE_JSON" <<'PY'
import json
import shlex
import sys

profile_path = sys.argv[1]

with open(profile_path, encoding="utf-8") as fh:
    profile = json.load(fh)

for field in ("build_config", "bazel_target"):
    value = profile.get(field)
    if value is None:
        print(f"{field.upper()}=''")
    elif isinstance(value, str) and value:
        print(f"{field.upper()}={shlex.quote(value)}")
    else:
        raise SystemExit(
            f"{profile_path}: profile field {field!r} must be a non-empty string or null"
        )
PY
)"

if [ ! -f "$GKI_DEFCONFIG" ]; then
  echo "Missing base ACK defconfig: $GKI_DEFCONFIG" >&2
  exit 1
fi

GKI_DEFCONFIG_SHA_BEFORE="$(sha256sum "$GKI_DEFCONFIG" | awk '{print $1}')"

python3 - "$DEFAULT_FRAGMENT" "$USER_FRAGMENT" "$GENERATED_FRAGMENT" "$REQUIRED_FRAGMENT" <<'PY'
from pathlib import Path
import sys

default_fragment = Path(sys.argv[1])
user_fragment = Path(sys.argv[2])
generated_fragment = Path(sys.argv[3])
required_fragment = Path(sys.argv[4])

def read_normalized(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")

parts = [
    "# Generated by scripts/prepare-private-fragment.sh\n"
    "# Layer order: base ACK defconfig, CoreShift default fragment, user private.fragment last\n"
    "\n"
]

default_text = read_normalized(default_fragment)
user_text = read_normalized(user_fragment)

if default_text:
    parts.append(default_text if default_text.endswith("\n") else default_text + "\n")

if user_text:
    parts.append(user_text if user_text.endswith("\n") else user_text + "\n")

final_text = "".join(parts)
generated_fragment.write_text(final_text, encoding="utf-8")
required_fragment.write_text(final_text, encoding="utf-8")
PY

if [ ! -f "$USER_FRAGMENT" ]; then
  echo "No user private.fragment found. To customize, copy configs/fragments/private.fragment.example to private.fragment."
fi

echo "Generated fragment: $GENERATED_FRAGMENT"
cat "$GENERATED_FRAGMENT"

if [ -n "$BAZEL_TARGET" ]; then
  if [ ! -f "$BUILD_BAZEL" ]; then
    echo "Missing BUILD.bazel for Bazel profile: $BUILD_BAZEL" >&2
    exit 1
  fi

  python3 - "$BUILD_BAZEL" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

if '"private.fragment"' in text or "'private.fragment'" in text:
    print(f"BUILD.bazel already exports private.fragment: {path}")
    raise SystemExit(0)

if text and not text.endswith("\n"):
    text += "\n"

text += '\nexports_files(["private.fragment"])\n'
path.write_text(text, encoding="utf-8")
print(f"Added private.fragment export to {path}")
PY
fi

if [ -n "$BUILD_CONFIG" ]; then
  if [ ! -f "$WORKSPACE_DIR/$BUILD_CONFIG" ]; then
    echo "Profile build_config not found in workspace: $WORKSPACE_DIR/$BUILD_CONFIG" >&2
    exit 1
  fi

  if [ ! -f "$MERGE_CONFIG_SH" ]; then
    echo "Missing merge_config helper: $MERGE_CONFIG_SH" >&2
    exit 1
  fi

  cat > "$WRAPPER_BUILD_CONFIG" <<EOF
# Generated by scripts/prepare-private-fragment.sh
. "\${ROOT_DIR}/${BUILD_CONFIG}"

CORESHIFT_ORIGINAL_PRE_DEFCONFIG_CMDS="\${PRE_DEFCONFIG_CMDS:-}"
CORESHIFT_ORIGINAL_POST_DEFCONFIG_CMDS="\${POST_DEFCONFIG_CMDS:-}"
CORESHIFT_PRIVATE_DEFCONFIG_CMD='cp "\${ROOT_DIR}/common/arch/arm64/configs/gki_defconfig" "\${ROOT_DIR}/common/arch/arm64/configs/coreshift_gki_defconfig" && "\${ROOT_DIR}/common/scripts/kconfig/merge_config.sh" -m -r "\${ROOT_DIR}/common/arch/arm64/configs/coreshift_gki_defconfig" "\${ROOT_DIR}/common/private.fragment"'

if [ -n "\${CORESHIFT_ORIGINAL_PRE_DEFCONFIG_CMDS}" ]; then
  PRE_DEFCONFIG_CMDS="\${CORESHIFT_ORIGINAL_PRE_DEFCONFIG_CMDS} && \${CORESHIFT_PRIVATE_DEFCONFIG_CMD}"
else
  PRE_DEFCONFIG_CMDS="\${CORESHIFT_PRIVATE_DEFCONFIG_CMD}"
fi

POST_DEFCONFIG_CMDS="\${CORESHIFT_ORIGINAL_POST_DEFCONFIG_CMDS}"
DEFCONFIG=coreshift_gki_defconfig

unset CORESHIFT_ORIGINAL_PRE_DEFCONFIG_CMDS
unset CORESHIFT_ORIGINAL_POST_DEFCONFIG_CMDS
unset CORESHIFT_PRIVATE_DEFCONFIG_CMD
EOF

  GKI_DEFCONFIG_SHA_AFTER="$(sha256sum "$GKI_DEFCONFIG" | awk '{print $1}')"
  if [ "$GKI_DEFCONFIG_SHA_BEFORE" != "$GKI_DEFCONFIG_SHA_AFTER" ]; then
    echo "Base ACK defconfig changed while preparing wrapper: $GKI_DEFCONFIG" >&2
    exit 1
  fi

  echo "Generated wrapper build config: $WRAPPER_BUILD_CONFIG"
  cat "$WRAPPER_BUILD_CONFIG"
fi

